version: "3.7"
services:
  postgresql:
    image: postgres
    container_name: postgresql_voucherpool
    ports:
      - 5433:5432
    networks:
      - voucherpool-network
    environment:
      - POSTGRES_USER=voucherpool
      - POSTGRES_PASSWORD=voucherpool
      - POSTGRES_DB=voucherpool
  voucherpool:
    image: ghcr.io/mjchi7/voucherpool:0.0.1-snapshot
    container_name: voucherpool-service
    ports:
      - 8080:8080
    environment:
      - spring_profiles_active=prod
    networks:
      - voucherpool-network

networks:
  voucherpool-network:
    name: voucherpool-network
